defaults:
  - dataset: libero_90
  - model: uwm
  - template_train_robomimic
  - _self_

model:
  num_registers: 24

model_path: "/tmp/matthewh6/uwm/logdir/uwm/libero_90/pretrain/0/models.pt"
libero_10_data_dir: "/scr/matthewh6/LIBERO/libero/datasets/libero_10"

model_calls: 3